version: "2.19.1"
services:
    database:
        build: database/
        ports: 
            - 3306:3306
        #Lanzamos comando para autenticaci칩n con contrase침a desde mysql
        command: --default-authentication-plugin=mysql_native_password 
        #Variables
        environment:
            MYSQL_DATABASE: algaba01
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        volumes:
            #sincronizaci칩n bbdd
            - ./db:/docker-entrypoint-initdb.d
        networks:
            - default
    web:
        build: web/
        ports: 
            - 80:80
        volumes:
            - ./public:/var/www/html
        links:
            - database
        #red de conexi칩n de los contenedores
        networks:
            - default
    adminphp:
        build: adminphp/
        links: 
            - database
        ports:
            - 8000:80
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
